import React from 'react'

export const Footer = () => (
  <>
    <footer>
      <div className="pb-4">
        &copy; {new Date().getFullYear()}, Built by
        {` `}
        <a
          href="https://www.linkedin.com/in/jgallardo2600/"
          target="_blank"
          rel="noreferrer"
        >Juan Gallardo</a>
      </div>
      <div>
        Images are generated by AI and edited with photoshop.
      </div>
    </footer>
  </>
)
